OpenAI:
  base_url: https://api.openai.com/v1
  api_key: 

DashScope:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: 

Volces:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  api_key: 

Silicon:
  base_url: https://api.siliconflow.cn/v1
  api_key: 

DeepSeek:
  base_url: https://api.deepseek.com/v1
  api_key: 

GLM:
  base_url: https://open.bigmodel.cn/api/paas/v4
  api_key: 

MoonShot:
  base_url: https://api.moonshot.cn/v1
  api_key: 

Local:
  base_url: http://localhost:8000/v1
  api_key: 111111

Tavily:
  api_key: 

LangSmith:
  api_key: